//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC.WCF.Client.ICWcfService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICWcfService._ICWcfService", CallbackContract=typeof(IC.WCF.Client.ICWcfService._ICWcfServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    internal interface _ICWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/__ICWcfService/SendMessage", ReplyAction="http://tempuri.org/__ICWcfService/SendMessageResponse")]
        IC.Core.MessageResponse SendMessage(IC.Core.MessageRequest messageRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/__ICWcfService/SendMessage", ReplyAction="http://tempuri.org/__ICWcfService/SendMessageResponse")]
        System.Threading.Tasks.Task<IC.Core.MessageResponse> SendMessageAsync(IC.Core.MessageRequest messageRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/__ICWcfService/RegisterClient", ReplyAction="http://tempuri.org/__ICWcfService/RegisterClientResponse")]
        void RegisterClient(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/__ICWcfService/RegisterClient", ReplyAction="http://tempuri.org/__ICWcfService/RegisterClientResponse")]
        System.Threading.Tasks.Task RegisterClientAsync(string clientId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface _ICWcfServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/_ICWcfService/SendMessageToClient", ReplyAction="http://tempuri.org/_ICWcfService/SendMessageToClientResponse")]
        IC.Core.MessageResponse SendMessageToClient(IC.Core.MessageRequest messageRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface _ICWcfServiceChannel : IC.WCF.Client.ICWcfService._ICWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class _ICWcfServiceClient : System.ServiceModel.DuplexClientBase<IC.WCF.Client.ICWcfService._ICWcfService>, IC.WCF.Client.ICWcfService._ICWcfService {
        
        public _ICWcfServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public _ICWcfServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public _ICWcfServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public _ICWcfServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public _ICWcfServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public IC.Core.MessageResponse SendMessage(IC.Core.MessageRequest messageRequest) {
            return base.Channel.SendMessage(messageRequest);
        }
        
        public System.Threading.Tasks.Task<IC.Core.MessageResponse> SendMessageAsync(IC.Core.MessageRequest messageRequest) {
            return base.Channel.SendMessageAsync(messageRequest);
        }
        
        public void RegisterClient(string clientId) {
            base.Channel.RegisterClient(clientId);
        }
        
        public System.Threading.Tasks.Task RegisterClientAsync(string clientId) {
            return base.Channel.RegisterClientAsync(clientId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICWcfService.__ICWcfService")]
    internal interface @__ICWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/__ICWcfService/SendMessage", ReplyAction="http://tempuri.org/__ICWcfService/SendMessageResponse")]
        IC.Core.MessageResponse SendMessage(IC.Core.MessageRequest messageRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/__ICWcfService/SendMessage", ReplyAction="http://tempuri.org/__ICWcfService/SendMessageResponse")]
        System.Threading.Tasks.Task<IC.Core.MessageResponse> SendMessageAsync(IC.Core.MessageRequest messageRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/__ICWcfService/RegisterClient", ReplyAction="http://tempuri.org/__ICWcfService/RegisterClientResponse")]
        void RegisterClient(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/__ICWcfService/RegisterClient", ReplyAction="http://tempuri.org/__ICWcfService/RegisterClientResponse")]
        System.Threading.Tasks.Task RegisterClientAsync(string clientId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface @__ICWcfServiceChannel : IC.WCF.Client.ICWcfService.@__ICWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class @__ICWcfServiceClient : System.ServiceModel.ClientBase<IC.WCF.Client.ICWcfService.@__ICWcfService>, IC.WCF.Client.ICWcfService.@__ICWcfService {
        
        public @__ICWcfServiceClient() {
        }
        
        public @__ICWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public @__ICWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public @__ICWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public @__ICWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IC.Core.MessageResponse SendMessage(IC.Core.MessageRequest messageRequest) {
            return base.Channel.SendMessage(messageRequest);
        }
        
        public System.Threading.Tasks.Task<IC.Core.MessageResponse> SendMessageAsync(IC.Core.MessageRequest messageRequest) {
            return base.Channel.SendMessageAsync(messageRequest);
        }
        
        public void RegisterClient(string clientId) {
            base.Channel.RegisterClient(clientId);
        }
        
        public System.Threading.Tasks.Task RegisterClientAsync(string clientId) {
            return base.Channel.RegisterClientAsync(clientId);
        }
    }
}
